### ISSUE TITLE
How can i parse two different cgmes profiles and merge them

### ISSUE THREAD

**Issue by AnkurArohi** [RWTH-IFHT/cimpyorm#11]
I want to parse two different Cgmes profiles stored in my disk to database and then export it to pandapower data models
Is this possible?

**Comment by TOffergeld** [comment]
Hi @AnkurArohi, sorry about the late reply. Is this still relevant for you?

CIMPyORM can be used to read multiple CGMES profiles (at least as long there are no UUID conflicts) if they are contained in the same folder/archive.

CIMPyORM cannot create a pandapower data model on its own, you would have to go through the individual CIM objects and create the appropriate pandapower objects.

**Comment by AnkurArohi** [comment]
Hi @TOffergeld 

Thanks for the reply so CIMpyORM will lead to python Objects?

**Comment by TOffergeld** [comment]
That's right. There is some (limited) documentation at [here](https://cimpyorm.readthedocs.io/en/latest/index.html).

If you have loaded a dataset, you can access, e.g. all `ACLineSegments` (provides an iterable) with
```python
db_session, model = parse(r"path_to_dataset")
acl = db_session.query(model.ACLineSegment).all()
```
and access their properties
```python
for l in acl:
    print(l.r) # Print the ACLineSegment's resistance
```

**Comment by AnkurArohi** [comment]
ok, so it is saved in database, when i load the DB I can also simply access it right ?
For example I could convert the DB Objects into csv and so on

**Comment by TOffergeld** [comment]
Yes, when you load a dataset, CIMPyORM will create a SQLite database (by default in the current working directory, named `out.db`) that you can open in any database explorer that can work with SQLite. The `db_session` object is an SQLAlchemy object that is associated with a database engine in the background (as mentioned, SQLite is the default). You should also be able to export tables from there as csv.

**Comment by AnkurArohi** [comment]
Thanks @TOffergeld
