### ISSUE TITLE
TypeError: declarative_base() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by FGH-Froehlich** [RWTH-IFHT/cimpyorm#16]
Hey there, 

i wanted to use cimpyorm to read out some CGMES grid data and modify them in python, but i was not able to run the program. I am using a windows machine with python 3.10.11 and cimpyorm 10.1. When i execute following code: 

```
import cimpyorm

if __name__ == "__main__":
    test2, model = cimpyorm.parse(r"grid_data/Export.xml")
```

an error occurs. It says: 

> TypeError: declarative_base() takes 0 positional arguments but 1 was given

as in the Title of this issue. I also checked using python 3.9 and 3.11, with the same results.

**Comment by tuscaonline** [comment]
Hi,
I add sqlalchemy = "<=1.3.15" into my requierement file. and it work for me.

**Comment by FGH-Froehlich** [comment]
Hey,
thank you very much, that solved the problem.
